export default [
  {
    name: "0",
    src: "0.webp",
    screens: [{ name: "0_0", src: "0_0.webp" }],
  },
  {
    name: "1",
    src: "1.webp",
    screens: [
      { name: "1_0", src: "1_0.webp" },
      { name: "1_1", src: "1_1.webp" },
      { name: "1_2", src: "1_2.webp" },
      { name: "1_3", src: "1_3.webp" },
      { name: "1_4", src: "1_4.webp" },
      { name: "1_5", src: "1_5.webp" },
    ],
  },
  {
    name: "2",
    src: "2.webp",
    screens: [
      { name: "2_0", src: "2_0.webp" },
      { name: "2_1", src: "2_1.webp" },
      { name: "2_2", src: "2_2.webp" },
      { name: "2_3", src: "2_3.webp" },
      { name: "2_4", src: "2_4.webp" },
      { name: "2_5", src: "2_5.webp" },
    ],
  },
  {
    name: "3",
    src: "3.webp",
    screens: [
      { name: "3_0", src: "3_0.webp" },
      { name: "3_1", src: "3_1.webp" },
      { name: "3_2", src: "3_2.webp" },
      { name: "3_3", src: "3_3.webp" },
      { name: "3_4", src: "3_4.webp" },
      { name: "3_5", src: "3_5.webp" },
      { name: "3_6", src: "3_6.webp" },
      { name: "3_7", src: "3_7.webp" },
      { name: "3_8", src: "3_8.webp" },
      { name: "3_9", src: "3_9.webp" },
      { name: "3_10", src: "3_10.webp" },
      { name: "3_11", src: "3_11.webp" },
      { name: "3_12", src: "3_12.webp" },
      { name: "3_13", src: "3_13.webp" },
    ],
  },
  {
    name: "4",
    src: "4.webp",
    screens: [
      { name: "4_0", src: "4_0.webp" },
      { name: "4_1", src: "4_1.webp" },
      { name: "4_2", src: "4_2.webp" },
      { name: "4_3", src: "4_3.webp" },
      { name: "4_4", src: "4_4.webp" },
      { name: "4_5", src: "4_5.webp" },
    ],
  },
  {
    name: "5",
    src: "5.webp",
    screens: [{ name: "5_0", src: "5_0.webp" }],
  },
];
